curl --request DELETE \
    --url http://localhost:5075/catalog/3 \
    --header 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Im9IYWVZZml1Nk5mU0lBNlNnVXZsaCJ9.eyJpc3MiOiJodHRwczovL2Rldi0yb25icHR1cWhicWZwaHg1LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJmV1VqYzVjNVdlam1JMGxVMzYzZHNOaEtDSGlGbGR0TUBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9ydWJ5LXRodW5kZXIiLCJpYXQiOjE3NzcxMzA0NTEsImV4cCI6MTc3NzIxNjg1MSwic2NvcGUiOiJkZWxldGU6Y2F0YWxvZyIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyIsImF6cCI6ImZXVWpjNWM1V2VqbUkwbFUzNjNkc05oS0NIaUZsZHRNIiwicGVybWlzc2lvbnMiOlsiZGVsZXRlOmNhdGFsb2ciXX0.EclVGeYRzuTSSlVcqjqJiYy2KQ_76sMxJjql7eKZ1gpfYTveFN2DOyTzIePj5_EE0zxLFm4Ydr44uQluV9v75HtlBAYGTVJ1mkbpc3butpsk8nMh3KC9SZdw1KMGTWSzX8pe6muM1961wLaNId9STS51qgHVdQbX394KIMQPDtVMhVslqh_AUxc2GXstwOyUbJUD3T3Hm7iIN6qDqBw0qmypvJp6ZqkEDaQqLbQAhRUu7NqSOQDuCzsX7C6mvN1E19d368ttJ-NtrwI05CMoUDZvBKyyk9wPhsil0JHmpB1fXt-GSaogFiSZAmRrIjmpIAxI2UVhemR_P3P4yKA79g'
